// <auto-generated />
using System;
using Api.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20211122193210_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("categoria", "public");
                });

            modelBuilder.Entity("Models.Perfil", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("perfil", "public");
                });

            modelBuilder.Entity("Models.PerfilPermissao", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<long>("perfil_id")
                        .HasColumnType("bigint");

                    b.Property<int>("permissao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("perfil_id");

                    b.ToTable("perfil_permissao", "public");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("categoria_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("categoria_id");

                    b.ToTable("produto", "public");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("perfil_id")
                        .HasColumnType("bigint");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("refresh_token_expiry_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("perfil_id");

                    b.ToTable("usuario", "public");
                });

            modelBuilder.Entity("Models.PerfilPermissao", b =>
                {
                    b.HasOne("Models.Perfil", "perfil")
                        .WithMany()
                        .HasForeignKey("perfil_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("perfil");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.HasOne("Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.HasOne("Models.Perfil", "perfil")
                        .WithMany()
                        .HasForeignKey("perfil_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
