// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220406130038_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("documento")
                        .HasColumnOrder(3);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nome")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.HasIndex("documento")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Models.MovimentacaoEstoque", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("motivo_movimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("motivo_movimento")
                        .HasColumnOrder(2);

                    b.Property<long>("produto_id")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id")
                        .HasColumnOrder(6);

                    b.Property<int>("quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade")
                        .HasColumnOrder(4);

                    b.Property<string>("tipo_movimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_movimento")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("produto_id");

                    b.ToTable("movimentacao_estoque", (string)null);
                });

            modelBuilder.Entity("Models.Pedido", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("cliente_id")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<DateTime>("data_pedido")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_pedido")
                        .HasColumnOrder(3);

                    b.Property<string>("status_pedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_pedido")
                        .HasColumnOrder(2);

                    b.Property<long>("vendedor_id")
                        .HasColumnType("bigint")
                        .HasColumnName("vendedor_id")
                        .HasColumnOrder(5);

                    b.HasKey("id");

                    b.HasIndex("cliente_id");

                    b.HasIndex("vendedor_id");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Models.PedidoItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<long>("pedido_id")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id")
                        .HasColumnOrder(5);

                    b.Property<long>("produto_id")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id")
                        .HasColumnOrder(4);

                    b.Property<decimal>("quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade")
                        .HasColumnOrder(2);

                    b.Property<decimal>("valor_unitario_pago")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_unitario_pago")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("pedido_id");

                    b.HasIndex("produto_id");

                    b.ToTable("pedido_item", (string)null);
                });

            modelBuilder.Entity("Models.Perfil", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1L,
                            ativo = true,
                            data_criacao = new DateTime(2022, 4, 6, 10, 0, 37, 835, DateTimeKind.Local).AddTicks(6472),
                            descricao = "Admin"
                        },
                        new
                        {
                            id = 2L,
                            ativo = true,
                            data_criacao = new DateTime(2022, 4, 6, 10, 0, 37, 835, DateTimeKind.Local).AddTicks(6484),
                            descricao = "Colaborador"
                        });
                });

            modelBuilder.Entity("Models.PerfilPermissao", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<long>("perfil_id")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id")
                        .HasColumnOrder(3);

                    b.Property<string>("permissao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permissao")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.HasIndex("perfil_id");

                    b.ToTable("perfil_permissao", (string)null);
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("categoria_id")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao")
                        .HasColumnOrder(2);

                    b.Property<decimal>("valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("categoria_id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email")
                        .HasColumnOrder(4);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome")
                        .HasColumnOrder(2);

                    b.Property<long>("perfil_id")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id")
                        .HasColumnOrder(8);

                    b.Property<string>("refresh_token")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("refresh_token_expiry_time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refresh_token_expiry_time")
                        .HasColumnOrder(6);

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("senha")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("perfil_id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Models.Vendedor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("data_edicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_edicao")
                        .HasColumnOrder(101);

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("documento")
                        .HasColumnOrder(3);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nome")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.HasIndex("documento")
                        .IsUnique();

                    b.ToTable("vendedor", (string)null);
                });

            modelBuilder.Entity("Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Models.Produto", "produto")
                        .WithMany("movimentacoes")
                        .HasForeignKey("produto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Models.Pedido", b =>
                {
                    b.HasOne("Models.Cliente", "cliente")
                        .WithMany("pedidos")
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Vendedor", "vendedor")
                        .WithMany("pedidos")
                        .HasForeignKey("vendedor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("vendedor");
                });

            modelBuilder.Entity("Models.PedidoItem", b =>
                {
                    b.HasOne("Models.Pedido", "pedido")
                        .WithMany("pedido_itens")
                        .HasForeignKey("pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Models.PerfilPermissao", b =>
                {
                    b.HasOne("Models.Perfil", "perfil")
                        .WithMany("permissoes")
                        .HasForeignKey("perfil_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("perfil");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.HasOne("Models.Categoria", "categoria")
                        .WithMany("produtos")
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.HasOne("Models.Perfil", "perfil")
                        .WithMany("usuarios")
                        .HasForeignKey("perfil_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("perfil");
                });

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Navigation("produtos");
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("Models.Pedido", b =>
                {
                    b.Navigation("pedido_itens");
                });

            modelBuilder.Entity("Models.Perfil", b =>
                {
                    b.Navigation("permissoes");

                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.Navigation("movimentacoes");
                });

            modelBuilder.Entity("Models.Vendedor", b =>
                {
                    b.Navigation("pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
